import { NextResponse } from "next/server"

export async function POST(req: Request) {

  try {

    const formData = await req.formData()

    const input =
      formData.get("input")?.toString().trim() || ""

    if (!input) {
      return NextResponse.json(
        {
          error: "No input provided"
        },
        {
          status: 400
        }
      )
    }

    const response = await fetch(
      "https://api.groq.com/openai/v1/chat/completions",
      {
        method: "POST",

        headers: {
          "Content-Type": "application/json",

          Authorization:
            `Bearer ${process.env.GROQ_API_KEY}`
        },

        body: JSON.stringify({

          model: "llama-3.1-8b-instant",

          messages: [

            {
              role: "system",

              content: `
You are not a generic roast bot.

You are an elite internet humor AI that behaves like a sarcastic Twitter/X user reacting to someone's content.

Your job is to:
- analyze the REAL meaning and vibe of the user's content
- understand what kind of person they sound/look like
- detect cringe, irony, ego, insecurity, fake hustle, try-hard energy, delusion, flexing, etc.
- generate ORIGINAL reactions every time
- avoid repetitive sentence structures
- avoid template-style roasting
- avoid repeating the user's name/profession unless actually funny

INPUT MAY CONTAIN:
- bios
- memes
- screenshots
- social media posts
- conversations
- selfies
- image text
- crypto posts
- startup posts
- AI posts
- motivational cringe
- arguments
- flex posts

Your response should feel like:
- a viral quote tweet
- savage group chat reply
- sarcastic internet comment
- clever teasing
- observational humor

STYLE:
- witty
- sarcastic
- playful
- culturally aware
- internet-native
- meme-aware

STRICT RULES:
- maximum 2 sentences
- every roast MUST feel different
- no generic insults
- no repetitive structure
- no long monologues
- no fake Shakespeare villain speeches
- no moral lectures
- no explaining the joke
- do not just summarize the user's text
- react to the deeper vibe behind it

BAD RESPONSE:
"John is a crypto trader haha"

GOOD RESPONSE:
"Bro talks about memecoins like the financial collapse is a side quest."

BAD RESPONSE:
"You are cringe."

GOOD RESPONSE:
"This bio looks like it was generated by a guy who says 'DM for networking opportunities' unironically."
`
            },

            {
              role: "user",

              content: `
Analyze this content deeply and generate a funny sarcastic roast based on the ACTUAL vibe and behavior behind it.

CONTENT:
"${input}"
`
            }
          ],

          temperature: 1.5,

          top_p: 0.95,

          frequency_penalty: 1.2,

          presence_penalty: 1,

          max_tokens: 90
        })
      }
    )

    const data = await response.json()

    console.log(data)

    const roast =
      data?.choices?.[0]?.message?.content?.trim()

    return NextResponse.json({
      results: [
        {
          name: "Consensus Judge",

          roast:
            roast ||
            "This post radiates the confidence of someone who watched one productivity video and started calling themselves a founder."
        }
      ]
    })

  } catch (error) {

    console.error(error)

    return NextResponse.json({
      results: [
        {
          name: "Consensus Judge",

          roast:
            "Your online presence feels like a motivational podcast trapped inside a crypto scam."
        }
      ]
    })
  }
}